# Generated by Django 4.0.2 on 2022-07-23 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название класса')),
                ('info', models.TextField(blank=True, verbose_name='Описание класса')),
            ],
            options={
                'verbose_name': 'Класс животных',
                'verbose_name_plural': 'Классы животных',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название отряда')),
                ('info', models.TextField(blank=True, verbose_name='Описание отряда')),
                ('classis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoowikipedia.classis')),
            ],
            options={
                'verbose_name': 'Отряд животных',
                'verbose_name_plural': 'Отряды животных',
                'ordering': ['name'],
            },
        ),
    ]
