# Generated by Django 4.0.2 on 2022-08-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoowikipedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название семейства')),
                ('info', models.TextField(blank=True, verbose_name='Описание семейства')),
                ('ordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoowikipedia.ordo')),
            ],
            options={
                'verbose_name': 'Семейство животных',
                'verbose_name_plural': 'Семейства животных',
                'ordering': ['name'],
            },
        ),
    ]
