# Generated by Django 4.0.2 on 2022-08-03 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoowikipedia', '0002_familia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название рода')),
                ('info', models.TextField(blank=True, verbose_name='Описание рода')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoowikipedia.familia')),
            ],
            options={
                'verbose_name': 'Род животных',
                'verbose_name_plural': 'Роды животных',
                'ordering': ['name'],
            },
        ),
    ]
