# Generated by Django 4.0.2 on 2022-08-04 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoowikipedia', '0003_genus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название вида')),
                ('info', models.TextField(blank=True, verbose_name='Описание вида')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoowikipedia.genus')),
            ],
            options={
                'verbose_name': 'Вид животных',
                'verbose_name_plural': 'Виды животных',
                'ordering': ['name'],
            },
        ),
    ]
